spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/BIKESERVICE
    password: mynewpassword
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    password: fbszkvgrwpspurxp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: aswin96777@gmail.com



